### ISSUE TITLE
PyPI version out of date - Python3 issue.

### ISSUE THREAD

**Issue by alex-wave** [brentp/fishers_exact_test#13]
Please could you update the version on PyPI to 0.1.5? It is currently 0.1.4, which doesn't appear to install correctly with pip / python 3.5.1. I've installed it manually using

pip install --user git+https://github.com/brentp/fishers_exact_test.git

and it then seems to work fine.

This then fixes my install of GOATools, which is dependent on this package.

Cheers!
Alex

**Comment by fabioticconi** [comment]
@brentp a little nudge in your direction: can 0.1.5 be pushed, or are there outstanding issues?

**Comment by brentp** [comment]
I just pushed 0.1.5, please let me know if you have any problems.

**Comment by fabioticconi** [comment]
Many thanks!

**Comment by alex-wave** [comment]
Thank you very much!

(I'll close this now.)
