### ISSUE TITLE
Specify and include license and license file

### ISSUE THREAD

**Issue by synapticarbors** [brentp/fishers_exact_test#21]
The `setup.py` says this package is released under a BSD license, but it does not specify which version. Also it would be good to include a copy of the license file and distribute it with the source distribution using a `MANIFEST.in` file as required by the BSD license:

https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template

**Comment by tanghaibao** [comment]
Addressed in fa770b9. Closing issue.
