### ISSUE TITLE
Tests failing on Python 3.3

### ISSUE THREAD

**Issue by johanneskoester** [brentp/fishers_exact_test#7]
Hi,
as the title says, your rfisher.py tests are currently failing with Python 3.3.
The calculated p-values do not even remotely match the expected ones.
Is there anything I can do to help with debugging?

**Comment by brentp** [comment]
I think this is related to 784b16c13f93dc7f9501e75709bfcec28e981e81 .
You could try setting epsilon = 1e-10
For me, that makes the tests pass. I don't remember why this is needed and don't want to keep changing back and forth until I understand what's going on (though 1e-10 does seem to give more consistent results).

**Comment by johanneskoester** [comment]
Well, perhaps you run into numerical issues with the smaller epsilon?

**Comment by johanneskoester** [comment]
Am I right that the change was introduces because of issue #1? If so, maybe there is a compromise between the two extremes such that yours and the test case of issue #1 succeed?

**Comment by brentp** [comment]
@johanneskoester the latest version has passed these tests. Let me know if you see any problems.

**Comment by johanneskoester** [comment]
Great, thank you!
